# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketCupCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_market_id', models.CharField(default='', max_length=63, verbose_name='Внутренее имя')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('symbol', models.CharField(max_length=15, verbose_name='Аббр')),
                ('rank', models.PositiveIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='Цена в USD')),
                ('volume_usd_24h', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('available_supply', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('total_supply', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
            ],
            options={
                'verbose_name': 'Монета CoinMarketCup',
                'verbose_name_plural': 'Монеты CoinMarketCup',
            },
        ),
        migrations.CreateModel(
            name='ExchangeCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.IntegerField(default=0)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Exchanges')),
            ],
            options={
                'verbose_name': 'Монета биржи',
                'verbose_name_plural': 'Монеты биржи',
            },
        ),
        migrations.CreateModel(
            name='ExchangeMainCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.ExchangeCoin')),
            ],
            options={
                'verbose_name': 'Главная монета биржи',
                'verbose_name_plural': 'Главные монеты биржи',
            },
        ),
        migrations.CreateModel(
            name='Extremum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экстремум',
                'verbose_name_plural': 'Экстремумы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=50)),
                ('globalTradeID', models.BigIntegerField()),
                ('tradeID', models.BigIntegerField()),
                ('orderNumber', models.BigIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=10)),
                ('total', models.DecimalField(decimal_places=8, max_digits=20)),
                ('our_total', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_ok', models.CharField(max_length=5)),
                ('date_time', models.DateTimeField()),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('main_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_main_coin', to='tradeBOT.ExchangeCoin')),
                ('second_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_second_coin', to='tradeBOT.ExchangeCoin')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='ToTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('total', models.DecimalField(decimal_places=8, max_digits=16)),
                ('total_f', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=16)),
                ('cause', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пара готовая к торговле',
                'verbose_name_plural': 'Пары готовые к торговле',
            },
        ),
        migrations.CreateModel(
            name='UserCoinShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.ExchangeCoin')),
                ('user_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange')),
            ],
            options={
                'verbose_name': 'Доля валюты',
                'verbose_name_plural': 'Доли валют',
            },
        ),
        migrations.CreateModel(
            name='UserMainCoinPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('main_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.ExchangeMainCoin')),
                ('user_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange')),
            ],
            options={
                'verbose_name': 'Главная монета пользователя',
                'verbose_name_plural': 'Главные монеты пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=5)),
                ('order_number', models.BigIntegerField()),
                ('main_coin_before_total', models.DecimalField(decimal_places=10, max_digits=20)),
                ('main_coin_before_free', models.DecimalField(decimal_places=10, max_digits=20)),
                ('main_coin_before_used', models.DecimalField(decimal_places=10, max_digits=20)),
                ('second_coin_before_total', models.DecimalField(decimal_places=10, max_digits=20)),
                ('second_coin_before_free', models.DecimalField(decimal_places=10, max_digits=20)),
                ('second_coin_before_used', models.DecimalField(decimal_places=10, max_digits=20)),
                ('main_coin_after_total', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('main_coin_after_free', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('main_coin_after_used', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('second_coin_after_total', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('second_coin_after_free', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('second_coin_after_used', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('total', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=5, max_digits=8)),
                ('fact_total', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('fact_fee', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=7, null=True)),
                ('is_ok', models.NullBooleanField(default=None)),
                ('interim_main_coin', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_cancel', models.DateTimeField(blank=True, default=None, null=True)),
                ('cancel_desc', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('to_close', models.BooleanField(default=False)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.Pair')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange')),
            ],
            options={
                'verbose_name': 'Ордер пользователя',
                'verbose_name_plural': 'Ордера пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('rate_of_change', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.Pair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange')),
            ],
            options={
                'verbose_name': 'Пара пользователя',
                'verbose_name_plural': 'Пары пользователей',
            },
        ),
        migrations.CreateModel(
            name='Сalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('depth_coef', models.DecimalField(decimal_places=8, max_digits=16)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bids', models.TextField(blank=True, null=True)),
                ('asks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.UserPair')),
            ],
        ),
        migrations.AddField(
            model_name='totrade',
            name='user_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.UserPair'),
        ),
        migrations.AddField(
            model_name='extremum',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeBOT.Pair'),
        ),
    ]
