# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info_frozen_key', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('t_type', models.CharField(max_length=20)),
                ('number', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('t_from', models.TextField()),
                ('t_to', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('block_hash', models.CharField(default=None, max_length=127, null=True)),
                ('hash', models.CharField(max_length=127)),
                ('comment', models.TextField(default='', null=True)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('details', models.CharField(default='', max_length=255, null=True)),
                ('usd_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('user_comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Транзакциия',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('used', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('free', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('conversions', models.CharField(max_length=255)),
                ('btc_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Балансы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=127)),
                ('apisecret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_script', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=True)),
                ('total_btc', models.DecimalField(decimal_places=8, max_digits=30)),
                ('total_usd', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('coefficient_of_depth', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Exchanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Биржа пользователя',
                'verbose_name_plural': 'Биржи пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserHoldings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('total_btc', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_usd', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История баланса',
                'verbose_name_plural': 'Истории балансов',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=511)),
                ('access_token', models.CharField(blank=True, default=None, max_length=511, null=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_btc', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_usd', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кошелёк пользователя',
                'verbose_name_plural': 'Кошельки пользователей',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Wallets'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchange'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('name', 't_type', 'hash')]),
        ),
    ]
