# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('driver', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('btc_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Финансы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserExchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=255)),
                ('apisecret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=True)),
                ('total_btc', models.DecimalField(decimal_places=8, max_digits=30)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Exchanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Биржа пользователя',
                'verbose_name_plural': 'Биржи пользователей',
            },
        ),
        migrations.AddField(
            model_name='userbalance',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserExchanges'),
        ),
    ]
