# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coin',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
    ]
