# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20170613_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchanges',
            name='error',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
