# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_userexchanges_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кошелёк пользователя',
                'verbose_name_plural': 'Кошельки пользователей',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('t_from', models.CharField(max_length=511)),
                ('t_to', models.CharField(max_length=511)),
                ('type', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('hash', models.CharField(max_length=511)),
                ('uw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.UserWallet')),
            ],
            options={
                'verbose_name': 'История кошелька',
                'verbose_name_plural': 'Истории кошельков',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Wallets'),
        ),
    ]
