# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20170614_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='address',
            field=models.CharField(default=None, max_length=511),
            preserve_default=False,
        ),
    ]
