# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_userwallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
    ]
