# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20170614_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='block_hash',
            field=models.CharField(default=None, max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='value',
            field=models.IntegerField(),
        ),
    ]
