# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20170614_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
