# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20170614_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='t_from',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='t_to',
            field=models.TextField(),
        ),
    ]
