# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20170615_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='access_token',
            field=models.CharField(blank=True, default=None, max_length=511),
        ),
    ]
