# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_userwallet_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='access_token',
            field=models.CharField(blank=True, default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
