# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20170620_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallethistory',
            options={'verbose_name': 'Транзакциии кошелька', 'verbose_name_plural': 'Транзакции кошельков'},
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='usd_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='user_comment',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
