# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20170620_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='user_comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
