# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20170620_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchanges',
            name='total_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
    ]
