# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0017_userwallet_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHoldings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('total_btc', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_usd', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История баланса',
                'verbose_name_plural': 'Истории балансов',
            },
        ),
    ]
