# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_userwallet_total_btc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together=set([('uw', 'number')]),
        ),
    ]
