# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_auto_20170629_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='block_hash',
            field=models.CharField(default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='details',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
